### PR TITLE
Webpack 4 support

### PR DESCRIPTION
**Pull request by burt202**
This seems to fix it for me. Let me know what you think

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@burt202 better get logic from https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/src/index.js#L117 to allow run plugin on `webpack@3` and `webpack@4`

**Comment by burt202** [comment]
Extended the PR based on your comment.

**Comment by evilebottnawi** [comment]
@burt202 run prettier on code for tests

**Comment by evilebottnawi** [comment]
```
[lint:eslint  ] /home/travis/build/itgalaxy/nunjucks-webpack-plugin/src/NunjucksWebpackPlugin.js
[lint:eslint  ]   106:32  error  'file' is defined but never used. Allowed unused args must match /^_/        no-unused-vars
[lint:eslint  ]   107:13  error  Variable 'compilationFileDependencies' should be initialized on declaration  init-declarations
[lint:eslint  ]   108:13  error  Variable 'addFileDependency' should be initialized on declaration            init-declarations
[lint:eslint  ]   112:31  error  'file' is already declared in the upper scope                                no-shadow
[lint:eslint  ]   115:31  error  'file' is already declared in the upper scope                                no-shadow
[lint:eslint  ]   118:20  error  'file' is already declared in the upper scope                                no-shadow
[lint:eslint  ]   118:20  error  'file' is already declared in the upper scope                                no-shadow
```
from CI, need fix

**Comment by burt202** [comment]
Thanks just saw this in travis, im on it. Would recommend adding https://www.npmjs.com/package/husky so I could catch this before pushing

**Comment by evilebottnawi** [comment]
@burt202 thanks :+1:

**Pull request merged**
